### PR TITLE
Updated create_database & query_database functions

### PR DESCRIPTION
**Pull request by chinmayayy**
The `return_json` bool parameter is added for user customized return type. I made similar changes to both the functions in database.py file. @pythonhubdev

### CODE REVIEW

**Review by pythonhubdev — APPROVED** [review]
Looks great 👍

**Comment by pythonhubdev** [comment]
@chinmayayy can you please format the file according to `pylint`. We have a pre-commit hook if you use that before commit these checks will run in your local. Just run `pre-commit install`

**Comment by pythonhubdev** [comment]
Don't close this PR let it be open. We can update the changes and merge this PR itself.

**Comment by chinmayayy** [comment]
I think it's failing again :(

**Comment by pythonhubdev** [comment]
No issues @chinmayayy I will merge it and fix the lint issues.

**Pull request merged**
